# Generated by Django 2.1.7 on 2023-04-27 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_userinfo'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pj_id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目ID')),
                ('pj_title', models.CharField(default='', max_length=100, unique=True, verbose_name='项目标题')),
                ('pj_sub', models.CharField(default='', max_length=300, verbose_name='项目简介')),
                ('pj_content', models.TextField(default='', verbose_name='项目描述')),
                ('pj_stack', models.CharField(default='', max_length=120, verbose_name='项目所用技术栈')),
                ('pj_is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pj_except_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目预算费用')),
                ('pj_except_day', models.IntegerField(default=0, verbose_name='项目期望开发周期（天）')),
                ('pj_actual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目实际费用')),
                ('pj_actual_day', models.IntegerField(default=0, verbose_name='项目实际开发周期（天）')),
                ('pj_status', models.SmallIntegerField(choices=[(1, '已创建待审核'), (2, '审核通过待开发'), (3, '开发中'), (4, '验收通过已完结')], default=1, verbose_name='项目状态')),
                ('pj_start_time', models.DateField(default=datetime.datetime.today, verbose_name='项目开始开发时间')),
                ('pj_end_time', models.DateField(default=datetime.datetime.today, verbose_name='项目完结时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='上一次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
